# Generated by Django 3.2.9 on 2021-11-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proracun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozicija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField(blank=True, null=True)),
                ('pozicija_sifra', models.TextField()),
                ('konto3', models.TextField()),
                ('pozicija_naziv', models.TextField()),
                ('planirano', models.FloatField(blank=True, null=True)),
                ('razdjel', models.TextField()),
                ('glava', models.TextField()),
                ('program', models.TextField()),
                ('aktivnost', models.TextField()),
                ('kategorija', models.TextField(blank=True, null=True)),
                ('podkategorija', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pozicija',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Proracun',
        ),
    ]
